const char HTTP_HEADER[] PROGMEM =
    "<head>"
    "<script type='text/javascript' src='/js/jquery-min.js'></script>"
    "<script type='text/javascript' src='/js/bootstrap.min.js'></script>"
    "<script type='text/javascript' src='/js/functions.js'></script>"
    "<script>function logoutButton() {"
    "var xhr = new XMLHttpRequest();"
    "xhr.open('GET', '/logout', true);"
    "xhr.send();"
    "setTimeout(function(){ window.open('/logged-out','_self'); }, 500);"
    "}</script>"
    "<link href='css/required.css' rel='stylesheet' type='text/css' />"
    "<link rel='icon' href='img/logo.png'>"
    "<title>{{pageName}} - Z2M</title>"
    " </head>"
    "<body>"
    "<nav class='navbar navbar-expand-lg navbar-light bg-info rounded' style='margin: 10px;'><a class='navbar-brand' href='/'><img src='img/logo.png'/> <strong>Zigbee2Mqtt</strong>"
    "</a>"
    "<button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarNavDropdown' aria-controls='navbarNavDropdown' aria-expanded='false' aria-label='Toggle navigation'>"
    "<span class='navbar-toggler-icon'></span>"
    "</button>"
    "<div id='navbarNavDropdown' class='collapse navbar-collapse justify-content-md-end'>"
    "<ul class='navbar-nav'>"
    "<li class='nav-item'>"
    "<a class='nav-link' href='/'><i class='glyphicon glyphicon-home'></i>&#x72B6;&#x6001;</a>"
    "</li>"
    "<li class='nav-item dropdown'>"
    "<a class='nav-link dropdown-toggle' href='#' id='navbarDropdown' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'><i  class='glyphicon glyphicon-cog'></i>&#x914D;&#x7F6E;</a>"
    "<div class='dropdown-menu' aria-labelledby='navbarDropdown'>"
    "<a class='dropdown-item' href='/general'><i class='glyphicon glyphicon-list-alt'></i>&#x901A;&#x7528;</a>"
    "<a class='dropdown-item' href='/serial'><i class='glyphicon glyphicon-wrench'></i>&#x4E32;&#x53E3;</a>"
    "<a class='dropdown-item' href='/ethernet'><i class='glyphicon glyphicon-globe'></i>&#x6709;&#x7EBF;</a>"    //有线网络配置主栏
    "<a class='dropdown-item' href='/wifi'><i class='glyphicon glyphicon-signal'></i>&#x65E0;&#x7EBF;</a>"
    "<a class='dropdown-item' href='/mqtt'><i class='glyphicon glyphicon-screenshot'></i>MQTT</a>"
    "</div>"
    "</li>"
    "<li class='nav-item dropdown'>"
    "<a class='nav-link dropdown-toggle' href='#' id='navbarDropdown' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'><i  class='glyphicon glyphicon-wrench'></i>&#x5DE5;&#x5177;</a>"
    "<div class='dropdown-menu' aria-labelledby='navbarDropdown'>"
    "<a class='dropdown-item' href='/logs'><i  class='glyphicon glyphicon-transfer'></i>&#x65E5;&#x5FD7;</a>"
    "<a class='dropdown-item' href='/fsbrowser'><i class='glyphicon glyphicon-floppy-disk'></i>&#x6587;&#x4EF6;</a>"
    "<a class='dropdown-item' href='/esp_update'><i class='glyphicon glyphicon-open'></i>&#x5347;&#x7EA7;</a>"
    //"<a class='dropdown-item' href='/updates'><i class='glyphicon glyphicon-open'></i>Update Zigbee</a>"          //废弃栏
    "<a class='dropdown-item' href='/reboot'><i class='glyphicon glyphicon-repeat'></i>&#x91CD;&#x542F;</a>"
    "</div>"
    "</li>"
    "</p>"
    "<li class='nav-item'>"
    "<a class='nav-link'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>"
    "</li>"
    "{{logoutLink}}"
    "</ul></div>"
    "</nav>";

const char LOGOUT_LINK[] PROGMEM = 
    "<li class='nav-item'>"
    "<a class='nav-link' href='javascript:logoutButton();'><i class='glyphicon glyphicon glyphicon-log-out'></i>Logout</a>"
    "</li>";

const char HTTP_WIFI[] PROGMEM =
    "<h2>{{pageName}}</h2>"
    "<div id='main' class='col-sm-12'>"
    "<div id='main' class='col-sm-6'><form method='POST' action='saveWifi'>"
    "<div class='form-group'>"
    "<div class='form-check'>"
    "<input class='form-check-input' id='wifiEnable' type='checkbox' name='wifiEnable' {{checkedWiFi}}>"
    "<label class='form-check-label' for='wifiEnable'>&#x542F;&#x7528;</label>"
    "</div>"
    "</div>"
    "<div class='form-group'>"
    "<label for='ssid'>&#x540D;&#x79F0;</label>"
    "<input class='form-control' id='ssid' type='text' name='WIFISSID' value='{{ssid}}'>"
    "</div>"
    "<div class='form-group'>"
    "<a onclick='scanNetwork();' class='btn btn-warning mb-2'>&#x626B;&#x63CF;</a>"
    "</div>"
    "<div class='form-group'>"
    "<div id='networks'></div>"
    "</div>"
    "<div class='form-group'>"
    "<label for='pass'>&#x5BC6;&#x7801;</label>"
    "<input class='form-control' id='pass' type='password' name='WIFIpassword' value='{{passWifi}}'>"
    "</div>"
    "<div class='form-group'>"
    "<div class='form-check'>"
    "<input class='form-check-input' id='dhcpWiFi' type='checkbox' name='dhcpWiFi' {{modeWiFi}}>"
    "<label class='form-check-label' for='dhcpWiFi'>DHCP</label>"
    "</div>"
    "</div>"
    "<div class='form-group'>"
    "<label for='ip'>IP</label>"
    "<input class='form-control' id='ip' type='text' name='ipAddress' value='{{ip}}'>"
    "</div>"
    "<div class='form-group'>"
    "<label for='mask'>&#x5B50;&#x7F51;&#x63A9;&#x7801;</label>"
    "<input class='form-control' id='mask' type='text' name='ipMask' value='{{mask}}'>"
    "</div>"
    "<div class='form-group'>"
    "<label for='gateway'>&#x7F51;&#x5173;</label>"
    "<input type='text' class='form-control' id='gateway' name='ipGW' value='{{gw}}'>"
    "</div>"
    "<button type='submit' class='btn btn-primary mb-2' name='save'>&#x4FDD;&#x5B58;</button>"
    "</form>";

const char HTTP_SERIAL[] PROGMEM =
    "<h2>{{pageName}}</h2>"
    "<div id='main' class='col-sm-12'>"
    "<div id='main' class='col-sm-6'><form method='POST' action='saveSerial'>"

    "<div class='form-group'>"
    "<label for='baud'>&#x4E32;&#x53E3;&#x901F;&#x5EA6;</label>"
    "<select class='form-control' id='baud' name='baud'>"
    "<option value='9600' {{selected9600}}>9600 bauds</option>"
    "<option value='19200' {{selected19200}}>19200 bauds</option>"
    "<option value='38400' {{selected38400}}>38400 bauds</option>"
    "<option value='57600' {{selected57600}}>57600 bauds</option>"
    "<option value='115200' {{selected115200}}>115200 bauds</option>"
    "</select>"
    "</div>"
    "<div class='form-group'>"
    "<label for='port'>&#x4E32;&#x53E3;&#x7AEF;&#x53E3;</label>"
    "<input class='form-control' id='port' type='number' name='port' min='100' max='65000' value='{{socketPort}}'>"
    "</div>"
    "<br><br>"
    "<button type='submit' class='btn btn-primary mb-2'name='save'>&#x4FDD;&#x5B58;</button>"
    "</form>";

    /*
const char HTTP_HELP[] PROGMEM =
    "<h2>Help</h2>"
    "<div id='main' class='col-sm-9'>"
    "<div id='help_btns'>"
    "<a href='#' class='btn btn-primary'><i class='glyphicon glyphicon-cog'></i>Primary</a>"
    "<a href='#' class='btn btn-secondary'><i class='glyphicon glyphicon-file'></i>Secondary</a>"
    "<a href='#' class='btn btn-success'><i class='glyphicon glyphicon-flag'></i>Success</a>"
    "<a href='#' class='btn btn-danger'><i class='glyphicon glyphicon-lock'></i>Danger</a>"
    "<a href='#' class='btn btn-warning'><i class='glyphicon glyphicon-tags'></i>Warning</a>"
    "</div>"
    "<script src='https://cdn.jsdelivr.net/npm/@webcomponents/webcomponentsjs@2/webcomponents-loader.min.js'></script>"
    "<script type='module' src='https://cdn.jsdelivr.net/gh/zerodevx/zero-md@1/src/zero-md.min.js'></script>"
    "<zero-md src='https://raw.githubusercontent.com/xyzroe/ZigStarGW-FW/main/README.md'></zero-md>"
    "</div>";
    */

const char HTTP_ERROR[] PROGMEM =
    "<h2>{{pageName}}</h2>"
    "<div id='main' class='col-sm-9'>"
    "</div>";

const char HTTP_ETHERNET[] PROGMEM =
    "<h2>{{pageName}}</h2>"
    "<div id='main' class='col-sm-12'>"
    "<div id='main' class='col-sm-6'><form method='POST' action='saveEther'>"
    "<div class='form-group'>"
    "<div class='form-check'>"
    "<input class='form-check-input' id='dhcp' type='checkbox' name='dhcp' {{modeEther}}>"
    "<label class='form-check-label' for='dhcp'>DHCP</label>"
    "</div>"
    "</div>"
    "<div class='form-group'>"
    "<label for='ip'>IP</label>"
    "<input class='form-control' id='ip' type='text' name='ipAddress' value='{{ipEther}}'>"
    "</div>"
    "<div class='form-group'>"
    "<label for='mask'>&#x5B50;&#x7F51;&#x63A9;&#x7801;</label>"
    "<input class='form-control' id='mask' type='text' name='ipMask' value='{{maskEther}}'>"
    "</div>"
    "<div class='form-group'>"
    "<label for='gateway'>&#x7F51;&#x5173;</label>"
    "<input type='text' class='form-control' id='gateway' name='ipGW' value='{{GWEther}}'>"
    "</div>"
    "<button type='submit' class='btn btn-primary mb-2'name='save'>&#x4FDD;&#x5B58;</button>"
    "</form>";

const char HTTP_GENERAL[] PROGMEM =
    "<h2>{{pageName}}</h2>"
    "<div id='main' class='col-sm-12'>"
    "<div id='main' class='col-sm-6'><form method='POST' action='saveGeneral'>"
    "<div class='form-group'>"
    "<label for='hostname'>&#x4E3B;&#x673A;&#x540D;</label>"
    "<input class='form-control' id='hostname' type='text' name='hostname' value='{{hostname}}'>"
    "</div>"
    "<div class='form-group'>"
    "<div class='form-check'>"
    "<input class='form-check-input' id='disableWeb' type='checkbox' name='disableWeb' {{disableWeb}}>"
    "<label class='form-check-label' for='disableWeb'>&#x4E32;&#x53E3;&#x8FDE;&#x63A5;&#x65F6;&#x7981;&#x7528;web&#x63A7;&#x5236;&#x9875;</label>"
    "<br>"
    "</div>"
    "</div>"
    "<div class='form-group'>"
    "<label for='refreshLogs'>&#x5237;&#x65B0;&#x63A7;&#x5236;&#x53F0;&#x65E5;&#x5FD7;&#x65F6;&#x95F4;</label>"
    "<input class='form-control' id='refreshLogs' type='text' name='refreshLogs' value='{{refreshLogs}}'>"
    "</div>"
    "<div class='form-group'>"
    "<div class='form-check'>"
    "<input class='form-check-input' id='webAuth' type='checkbox' name='webAuth' {{webAuth}}>"
    "<label class='form-check-label' for='webAuth'>&#x542F;&#x7528; Web &#x670D;&#x52A1;&#x5668;&#x8EAB;&#x4EFD;&#x9A8C;&#x8BC1;</label>"
    "<br>"
    "</div>"
    "</div>"
    "<div class='form-group'>"
    "<label for='webUser'>&#x7528;&#x6237;&#x540D;</label>"
    "<input class='form-control' id='webUser' type='text' name='webUser' value='{{webUser}}'>"
    "</div>"
    "<div class='form-group'>"
    "<label for='webPass'>&#x5BC6;&#x7801;</label>"
    "<input class='form-control' id='webPass' type='password' name='webPass' value='{{webPass}}'>"
    "</div>"
    "<button type='submit' class='btn btn-primary mb-2' name='save'>&#x4FDD;&#x5B58;</button>"
    "</form></div>"
    "</div>";

const char HTTP_ROOT[] PROGMEM =
    "<h2>{{pageName}}</h2>"
    "<div id='main' class='col-sm-12'>"
    "<div id='main' class='col-sm-6'>"
    "<div class='card'>"
    "<div class='card-header'>&#x901A;&#x7528;</div>"
    "<div class='card-body'>"
    "<div id='genConfig'>"
    "<strong>&#x4E32;&#x53E3;&#x8FDE;&#x63A5;&#x65F6;&#x95F4; : </strong>{{connectedSocket}}"
    "<br><strong>&#x8FD0;&#x884C;&#x65F6;&#x95F4; : </strong>{{uptime}}"
    "<br><strong>&#x6E29;&#x5EA6; : </strong>{{deviceTemp}} &deg;C"
    "<br><strong>&#x56FA;&#x4EF6;&#x7248;&#x672C; : </strong>" VERSION
    "<br><strong>&#x786C;&#x4EF6; : </strong>{{hwRev}}"    //硬件信息ETH显示栏
    "<br><strong>ESP32 &#x578B;&#x53F7; : </strong>{{espModel}}"
    "<br><strong>CPU : </strong>{{espCores}} cores @ {{espFreq}} MHz"
    "<br><strong>&#x95EA;&#x5B58; : </strong>{{espFlashSize}} Mb, {{espFlashType}}"
    "<br><strong>&#x7A7A;&#x95F2;&#x5185;&#x5B58; : </strong>{{espHeapFree}} / {{espHeapSize}} KiB"
    "</div>"
    "</div>"
    "</div><br>"     //有线网络配置子栏，主栏下面子信息显示
    "<div class='card'>"
    "<div class='card-header'>&#x6709;&#x7EBF;&#x7F51;&#x7EDC;</div>"
    "<div class='card-body'>"
    "<div id='ethConfig'>"
    "{{stateEther}}"
    "</div>"
    "</div>"
    "</div><br>"
    "<div class='card'>"
    "<div class='card-header'>&#x65E0;&#x7EBF;&#x7F51;&#x7EDC;</div>"
    "<div class='card-body'>"
    "<div id='wifiConfig'>"
    "{{stateWifi}}"
    "</div>"
    "</div>"
    "</div><br>"
    "<div class='card'>"
    "<div class='card-header'>MQTT</div>"
    "<div class='card-body'>"
    "<div id='mqttConfig'>"
    "{{stateMqtt}}"
    "</div>"
    "</div>"
    "</div><br>"
    "</div>"
    "</div>";


const char HTTP_UPDATE[] PROGMEM =
    "<form method='POST' action='#' enctype='multipart/form-data' id='upload_form'>"
    "<input type='file' name='update' id='file' onchange='sub(this)' style=display:none accept='.bin'>"
    "<label id='file-input' for='file'>  ----&#x9009;&#x62E9;&#x6587;&#x4EF6;----</label>"
    "<input type='submit' class='btn btn-danger mb-2' value='&#x5347;&#x7EA7;'>"
    "<br><br>"
    "<div id='prg'></div>"
    "<br><div id='prgbar'><div id='bar'></div></div><br></form>"
   /*
    "<div id='update_info'>"
    "<h4>&#x6700;&#x65B0;&#x7248;&#x672C;</h4>"
    "<div id='onlineupdate'>"
    "<h5 id=releasehead></h5>"
    "<div style='clear:both;'>"
    "<br>"
    "</div>"
    "<pre id=releasebody>Getting update information from GitHub...</pre>"
    "<div class='pull-right' style='text-align: center;'>"
    "<a class='pull-right' id='downloadupdate'>"
    "<button type='button' class='btn btn-success'>Download</button>"
    "</a>"
    "</div>"
    "</div>"
    "</div>"
    */
    "<div style='clear:both;'>"
    "<br>"
    "</div>"
    "<script language='javascript'>getLatestReleaseInfo();</script>"
    "<script>"
    "function sub(obj){"
    "var fileName = obj.value.split('\\\\');"
    "document.getElementById('file-input').innerHTML = '   '+ fileName[fileName.length-1];"
    "};"
    "$('form').submit(function(e){"
    "e.preventDefault();"
    "var form = $('#upload_form')[0];"
    "var data = new FormData(form);"
    "$.ajax({"
    "url: '/update',"
    "type: 'POST',"
    "data: data,"
    "contentType: false,"
    "processData:false,"
    "xhr: function() {"
    "var xhr = new window.XMLHttpRequest();"
    "xhr.upload.addEventListener('progress', function(evt) {"
    "if (evt.lengthComputable) {"
    "var per = evt.loaded / evt.total;"
    "$('#prg').html('&#x8FDB;&#x5EA6;: ' + Math.round(per*100) + '%');"
    "$('#bar').css('width',Math.round(per*100) + '%');"
    "}"
    "}, false);"
    "return xhr;"
    "},"
    "success:function(d, s) {"
    "console.log('success!');"
    "$('#prg').html('&#x4E0A;&#x4F20;&#x5B8C;&#x6210;&#xFF01;<br>&#x91CD;&#x542F;&#x4E2D;&#xFF01;');"
    "window.location.href='/';"
    "},"
    "error: function (a, b, c) {"
    "}"
    "});"
    "});"
    "</script>";

const char HTTP_MQTT[] PROGMEM =
    "<h2>{{pageName}}</h2>"
    "<div id='main' class='col-sm-12'>"
    "<div id='main' class='col-sm-6'><form method='POST' action='saveMqtt'>"
    "<div class='form-group'>"
    "<div class='form-check'>"
    "<input class='form-check-input' id='enb' type='checkbox' name='enable' {{mqttEnable}}>"
    "<label class='form-check-label' for='enb'>&#x542F;&#x7528;</label>"
    "</div>"
    "</div>"
    "<div class='form-group'>"
    "<label for='ip'>MQTT&#x7F51;&#x5173;</label>"
    "<input class='form-control' id='ip' type='text' name='server' value='{{mqttServer}}'>"
    "</div>"
    "<div class='form-group'>"
    "<label for='port'>&#x7AEF;&#x53E3;</label>"
    "<input class='form-control' id='port' type='number' name='port' min='100' max='65000' value='{{mqttPort}}'>"
    "</div>"
    "<div class='form-group'>"
    "<label for='user'>&#x7528;&#x6237;&#x540D;</label>"
    "<input class='form-control' id='user' type='text' name='user' value='{{mqttUser}}'>"
    "</div>"
    "<div class='form-group'>"
    "<label for='pass'>&#x5BC6;&#x7801;</label>"
    "<input class='form-control' id='pass' type='password' name='pass' value='{{mqttPass}}'>"
    "</div>"
    "<div class='form-group'>"
    "<label for='topic'>&#x4E3B;&#x9898;</label>"
    "<input class='form-control' id='topic' type='text' name='topic' value='{{mqttTopic}}'>"
    "</div>"
    /*"<div class='form-group'>"
    "<div class='form-check'>"
    "<input class='form-check-input' id='retain' type='checkbox' name='retain' {{mqttRetain}}>"
    "<label class='form-check-label' for='retain'>Retain</label>"
    "</div>"
    "</div>"*/
    "<div class='form-group'>"
    "<label for='port'>&#x5237;&#x65B0;&#x95F4;&#x9694;</label>"
    "<input class='form-control' id='interval' type='number' name='interval' min='0' max='3600' value='{{mqttInterval}}'>"
    "</div>"
    "<div class='form-group'>"
    "<div class='form-check'>"
    "<input class='form-check-input' id='discovery' type='checkbox' name='discovery' {{mqttDiscovery}}>"
    "<label class='form-check-label' for='discovery'>&#x81EA;&#x52A8;&#x53D1;&#x73B0;</label>"
    "</div>"
    "</div>"
    "<button type='submit' class='btn btn-primary mb-2'name='save'>&#x4FDD;&#x5B58;</button>"
    "</form>";